### ISSUE TITLE
Use unrestricted app cred for capi mgmt node and 2ndary restricted app creds for capo and for CSI and OCCM

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#109]
We should have capability to create further app creds for clusters on the capi mgmt node.
This is a first step into managing clusters across clouds from the same mgmt node.

We should then create two (!) restricted app creds per cluster:
- One is for capo: This one can not be accessed / abused from within the workload cluster.
- One if for CSI and OCCM, allowing create OpenStack resources (loadbalancers, volumes, ...) from within the workload cluster

The latter is subject to abuse if hostile users within the cluster want to do evil things. So be prepared to independently revoke these app creds.

**Comment by garloff** [comment]
This should also prepare for having multiple clouds configured in ~/.config/openstack/clouds.yaml and secrets.yaml and avoid assuming particular formatting of it. (It could as well have std user/password combo in there.) 

This also nicely decouples the need for OCCM clouds.yaml to have project_id (despite using appcreds, where std openstackclient does neither need nor tolerate project_id).

**Comment by garloff** [comment]
Work on deployment node done (we generate an unrestricted application credential, #177),
but not yet the creation of per-cluster app-creds.

**Comment by garloff** [comment]
This is fully addressed in PR #226.
Once the PR is merged, we can close this one.

**Comment by chess-knight** [comment]
@garloff can you close this one, please?
