### ISSUE TITLE
Fix healthcheck for controller-manager and scheduler for testcluster-admin@testcluster context

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#12]
```ubuntu@capi-mgmtcluster:~$ kubectl config use-context ${CLUSTER_NAME}-admin@${CLUSTER_NAME}
Switched to context "testcluster-admin@testcluster".
ubuntu@capi-mgmtcluster:~$ k get componentstatuses
NAME                 STATUS      MESSAGE                                                                                     ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused  
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: connect: connection refused  
etcd-0               Healthy     {"health":"true"} ```

This may or may not be cosmetical problem; the components run, but support an http*s* healthcheck on another port.
I suggest to fix this or at least make double sure that this is really only a cosmetic issue.

**Comment by curx** [comment]
the "componentstatus" (cs) is deprecated since v1.19 see [changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md) and 
https://github.com/kubernetes/enhancements/issues/553

Currently it is more "cosmetic" since the cs is removed.

**Comment by garloff** [comment]
Ah, OK, thanks. We are using 1.18 here though ...
Whether or not the cs command is deprecated: The question is whether there is a useful healthcheck failing (which we get reported by cs but probably could retrieve in a different way) or whether cs indeed is triggering a healthcheck that should not even be triggered.
As said, the services seem fine. If the cs command is the only thing that is unaware, then we can indeed ignore this.
If cs is just the messenger, then we should better fix it (even if the messenger is deprecated).

**Comment by mxmxchere** [comment]
discussed again in SCS-Tech. Consent that this can be closed.
