### ISSUE TITLE
Option to deploy harbor

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#139]
We have the k8s-harbor repository that can be used to automate the deployment of harbor registry on SCS clusters.
We should offer this as an option.
To make it work, we need to:
* deploy_flux
* understand how to create working certs using cert-manager (which will likely need updating)
* create a testable setup for CI purposes and document how prod setups would work

The k8s-harbor repo references a comparably old version of harbor, we should also check whether we can update here.

**Comment by jschoone** [comment]
As discussed with @matofeder and @chess-knight this will be installed using [cluster-api-addon-provider-helm](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm)

**Comment by jschoone** [comment]
Hi @chess-knight, how's progress on this? Is it the [harbor branch from k8s-cluster-api-provider](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/tree/harbor)?

**Comment by chess-knight** [comment]
> Hi @chess-knight, how's progress on this? Is it the [harbor branch from k8s-cluster-api-provider](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/tree/harbor)?

Hi @jschoone, yeah it is that branch but I made little progress from there. Right now I investigated and implemented rate limit protection for scs harbor. Sorry, this issue probably shouldn't have doing status.
