### ISSUE TITLE
kube-proxy in kind-kind ending in Error (CrashloopBackoff)

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#18]
It appears to crash trying to write to /proc/sys/net/netfilter/nf_conntrack_max, which fails (permission denied).

**Comment by garloff** [comment]
It appears that the container does not have the rights to change sysctls ...
Setting the limit to the wanted 131072 manually on the VM helps the kube=proxy to work.
Not sure that it helps the overall failure

**Comment by garloff** [comment]
With this setting, the testcluster creation works again.

**Comment by curx** [comment]
see https://github.com/kubernetes-sigs/kind/issues/2240 more in detail

**Comment by garloff** [comment]
Thanks, Thorsten!
The error message was good enough that I could guess the solution -- I wish all errrors would be so easy to solve!
I guess the workaround is to just add a sysctl.d setting to the image (or inject it before we deploy kind).
Just adding to the deploy.sh won't work, as you'll need root privs ...

**Comment by curx** [comment]
We can update the [cloud-config](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/master/terraform/mgmtcluster.tf#L43)  to add the needed sysctl settings, to after the bootstrap the kind is ready to use.

**Comment by garloff** [comment]
Fixed by PR #20.
