### ISSUE TITLE
create_cluster.sh fails to wait for Cluster=Ready

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#208]
```
[kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/ecok8s-md-0-genw1](http://kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/ecok8s-md-0-genw1) created
secret/ecok8s-cloud-config unchanged
# Waiting for Cluster=Ready
error: no matching resources found
```
This happens occasionally, and primarily on previously created clusters.

**Comment by garloff** [comment]
I suspect the logic here to avoid unnecessary waits is just not robust enough.
TODO:
- Find test case to identify whether or not the suspicion is true
- If so, either simplify the logic and bear with the unnecessary waits OR handle the error case

**Comment by garloff** [comment]
It consistently waits long enough in my tests now -- can you confirm, Enrico?

**Comment by flyersa** [comment]
Will check and update

**Comment by garloff** [comment]
Any updates? I have not seen the issue any more although it only happened occasionally before ...
I guess slower clouds are better for reproduction ...

**Comment by flyersa** [comment]
Hi Kurt,

i could not replicate the problem so far. So seems to be working good now.

**Comment by garloff** [comment]
Thanks for testing, Enrico!
I'll close the issue then, please reopen in case this pops up again!
