### ISSUE TITLE
Allow the use of already existing CAPI images

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/k8s-cluster-api-provider#227]
It should be possible to use a CAPI image provided by the CSP as public image. This avoids the download and upload of CAPI images per project.

**Comment by garloff** [comment]
This is supported already.
If there are public or shared images with the name configured in `clusterctl.yaml` (`OPENSTACK_IMAGE_NAME`, defaults to `ubuntu-capi-image-${KUBERNETES_VERSION}`), then no image is downloaded and registered.
Closing, please reopen if this is not covered in the way you need and explain ...
