### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/k8s-cluster-api-provider#242]
There is no LICENSE file in this repository. Should be added.

**Comment by garloff** [comment]
Mixture of ASL-2.0 and CC-BY-SA-4.0 currently, resulting in complete works being CC-BY-SA-4.0.

**Comment by garloff** [comment]
Should try to relicense under ASL-2.0 to have a clean picture.
AI Kurt to track down contributors that have contributed under CC-BY-SA-4.0.

**Comment by garloff** [comment]
This has been addressed with PR #261.
