### ISSUE TITLE
Update to latest k8s versions

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#248]
Enable latest capi images for 1.21.x, 1.22.x, 1.23.x, 1.24.x.

**Comment by garloff** [comment]
Shouldn't there be a 1.24.3?

**Comment by garloff** [comment]
Document how to deal with old versions in SCS.

**Comment by garloff** [comment]
@mxmxchere , @matfechner -- could you look into the missing latest ubuntu-capi images?

**Comment by garloff** [comment]
Also: I think we should not remove the older capi images from the minio store.
* From the last 3 k8s versions (the supported versions), we should have several patchlevels
* From the old k8s versions, we should at least keep v1.old.latest
There is no doubt that there will be customers that depend on old versions ...

**Comment by garloff** [comment]
@matfechner  and @fynluk to recheck.

**Comment by garloff** [comment]
Any updates no the missing images?

**Comment by matfechner** [comment]
@garloff it should fixed with this PR  https://github.com/osism/k8s-capi-images/pull/137

**Comment by matfechner** [comment]
@garloff  And 1.25 with this PR https://github.com/osism/k8s-capi-images/pull/136

**Comment by garloff** [comment]
Build system @ OSISM needs fixing.

**Comment by berendt** [comment]
Build system fixed with https://github.com/osism/k8s-capi-images/commit/50a1e8853bae46db557e78873302b8119ed73b8d. Latest images are uploading at the moment. 1.25 is now also available.

**Comment by garloff** [comment]
OK, thanks, Pull Request to also use these images in #267 .
