### ISSUE TITLE
Cluster Upgrade Documentation

### ISSUE THREAD

**Issue by flyersa** [SovereignCloudStack/k8s-cluster-api-provider#255]
Hey,

there were alot of changes recently. Can you please update the upgrade documentation to upgrade a existing cluster to a newer k8s version? Is is stil required to change all the namings manually? Maybe we can implement a upgrade_cluster.sh script?

**Comment by garloff** [comment]
The Upgrade guide is being written in the branch feat/Upgrade-Guide.
Feedback welcome.
https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/feat/Upgrade-Guide/doc/Upgrade-Guide.md

**Comment by jschoone** [comment]
Upgrade guide can be found now here: https://docs.scs.community/docs/k8s-cluster-api-provider/doc/Upgrade-Guide
