### ISSUE TITLE
K8s 1.25.x deployment fails / Upstream container image registry moved

### ISSUE THREAD

**Issue by aov-arnold** [SovereignCloudStack/k8s-cluster-api-provider#303]
Deployment gets stuck during bootstrap of first control plane because coredns container image cannot be pulled.

**Example log of containerd on control plane:**
`
Oct 18 07:02:29 private-1-25-x-control-plane-genc01-z82cd containerd[542]: time="2022-10-18T07:02:29.140119964Z" level=error msg="PullImage \"k8s.gcr.io/coredns:v1.9.3\" failed" error="rpc error: code = NotFound desc = failed to pull and unpack image \"k8s.gcr.io/coredns:v1.9.3\": failed to resolve reference
`

Registry k8s.gcr.io moved to registry.k8s.io in K8s 1.25 according to: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#moved-container-registry-service-from-k8sgcrio-to-registryk8sio.

**Comment by aov-arnold** [comment]
@garloff
Is this relevant? Maybe changing the registry is not enough? https://github.com/kubernetes-sigs/image-builder/pull/956#issuecomment-1226094042

**Comment by garloff** [comment]
Kubeadm knows how to find coredns if the registry host is correct.
(I wonder though if we can just remove that setting completely, as kubeadm has that knowledge.)

**Comment by aov-arnold** [comment]
Relying on the kubeadm defaults sounds good as long as we are not using a private registry or pull-through cache.

**Comment by garloff** [comment]
#301 has been merged to main and the maintained/v4.x and v4.0.x branches, addressing this issue.
1.25.3 has been validated successfully with sonobuoy using calico-3.24.1 as CNI.

**Comment by garloff** [comment]
Another note for completeness:
1.24.x/calico also continues to pass sonobuoy without any failed tests.
1.25.x/cilium continues to have the 4 documented fails:
```
Failed tests:                                                         
[It] [sig-network] Services should have session affinity work for service with type clusterIP [LinuxOnly] [Conformance]                     
[It] [sig-network] Services should have session affinity timeout work for service with type clusterIP [LinuxOnly] [Conformance]             
[It] [sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]                                                                                                                             
[It] [sig-network] Services should be able to switch session affinity for service with type clusterIP [LinuxOnly] [Conformance]             
```
