### ISSUE TITLE
Update flux to the latest version ahead of R4

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#335]
As k8s user that opts-in to get flux2 deployed along with the cluster, I'd like to get the current stable version.

**Comment by chess-knight** [comment]
Hello @garloff.
I found that we do not pin a flux version. Should I implement some kind of version pinning? Thanks!

**Comment by garloff** [comment]
Ah, OK.
We should introduce a tristate "false", "vX.Y,Z", "true" with true meaning the recommended latest version tested by us.
Not pinning at all is somewhat risky, as it might break if upstream changes things ...
This has not bit us because flux2 seems to have been careful thus far. Nevertheless, pinning would be good.
