### ISSUE TITLE
worker/control vms not starting on cluster_create

### ISSUE THREAD

**Issue by flyersa** [SovereignCloudStack/k8s-cluster-api-provider#346]
Hello,

i have the issue with a client that on cluster_create.sh no VMs are spooling up. The Loadbalancer is created and finished, but the task to start the actual vms is timing out. 

# apply configuration and deploy cluster burda-2
cluster.cluster.x-k8s.io/burda-2 unchanged
openstackcluster.infrastructure.cluster.x-k8s.io/burda-2 unchanged
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/burda-2-control-plane unchanged
openstackmachinetemplate.infrastructure.cluster.x-k8s.io/capi-burda-2-control-plane-genc01 unchanged
machinedeployment.cluster.x-k8s.io/capi-burda-2-md-0-no1 unchanged
openstackmachinetemplate.infrastructure.cluster.x-k8s.io/capi-burda-2-md-0-genw01 unchanged
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io/capi-burda-2-md-0-genw01 unchanged
secret/burda-2-cloud-config unchanged
# Waiting for Cluster=Ready
kubeadmcontrolplane.controlplane.cluster.x-k8s.io/burda-2-control-plane condition met

and here it times out after a while and i do not see any vm being created in openstack, the image is there and available.

is there a way to get some logs to see where it is timing out, it may be a network issue? i can reach all openstack apis fine from the capi node without any problems.

**Comment by flyersa** [comment]
the only thing i can see is something with no valid providerID, outside of thsi the logs are not very fruitful

I0301 09:35:04.965853       1 machine_controller_phases.go:224] "Bootstrap provider is not ready, requeuing" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" machine="default/capi-burda-2-md-0-no1-6d6b875bcb-b82zw" namespace="default" name="capi-burda-2-md-0-no1-6d6b875bcb-b82zw" reconcileID=99c4f316-5825-4897-8f4e-8a56428e7de2 cluster="burda-2"
I0301 09:35:04.970557       1 machine_controller_phases.go:286] "Infrastructure provider is not ready, requeuing" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" machine="default/capi-burda-2-md-0-no1-6d6b875bcb-b82zw" namespace="default" name="capi-burda-2-md-0-no1-6d6b875bcb-b82zw" reconcileID=99c4f316-5825-4897-8f4e-8a56428e7de2 cluster="burda-2"
I0301 09:35:04.970721       1 machine_controller_noderef.go:49] "Cannot reconcile Machine's Node, no valid ProviderID yet" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" name="capi-burda-2-md-0-no1-6d6b875bcb-b82zw" reconcileID=99c4f316-5825-4897-8f4e-8a56428e7de2 machine="capi-burda-2-md-0-no1-6d6b875bcb-b82zw" namespace="default" cluster="burda-2"

**Comment by garloff** [comment]
Hi @flyersa ,
this was the environment we looked at together in Nuremberg, right?
Does this problem persist after you have fixed the way AZs are created and named?

**Comment by flyersa** [comment]
Hi Kurt,

yes this was the issue we looked at the hackathon, sorry i wasnt able to test so far. Will check later today on that. But im sure it will be gone.

**Comment by garloff** [comment]
I'll close this, please reopen if it turns out not to be fixed.
