### ISSUE TITLE
capi: Creating LBs until running out of quota if LB health-mon prevents creation

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#365]
So, when we enable `use_ovn_lb_provider=auto`, the LB creation in front of the ingress is not successful.
capi is "clever" enough to create a new LB every 5 mins without cleaning out the old, failed one.
This is really bad behavior, unfortunately not untypical for capi/capo, see e.g. #283 for a similar pattern.

**Comment by chess-knight** [comment]
This [upstream issue](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1404) is probably related to this.
