### ISSUE TITLE
Epic: Support custom CA with k8s-cluster-api-provider

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#372]
When running a SCS cloud, you should use true certficates to protect the OpenStack API. Possibly with Let's Encrypt. Sometimes this is not easy to do, e.g. in a Cloud-in-a-Box system. In that case, this Epic is relevant.

As Cluster Operator on top of an SCS reference IaaS with a custom CA, I want to be able to create k8s clusters using the SCS KaaS reference implementation without going through undocumented manual steps.
TODO: Automate detection for this scenario and handle it as automatically as is feasible with reasonable effort. Document this well, especially if there are any remaining manual steps.

- [x] #373 
- [x] #374
- [x] #375
- [x] #376
- [x] #488

**Comment by chess-knight** [comment]
The last issue #488 is solved by #499, so epic can be closed.
