### ISSUE TITLE
Set CLUSTER_API_OPENSTACK_INSTANCE_CREATE_TIMEOUT

### ISSUE THREAD

**Issue by JensAc** [SovereignCloudStack/k8s-cluster-api-provider#382]
Hi :wave: , 
I had some trouble with a k8s update from 1.23.x to 1.24.x, as the capo-controller-manager was running into the "machine create timeout" which is set to 5min by default. I felt like setting `CLUSTER_API_OPENSTACK_INSTANCE_CREATE_TIMEOUT` to 10 does the trick. I am wondering, whether it is possible to set this variable with the tools provided in this repo and would really appreciate any comment :slightly_smiling_face:.

**Comment by garloff** [comment]
Thanks for the suggestion, Jens!
We don't have that parameter exposed in the cluster-template.yaml / clusterctl.yaml templating mechanism.
Where exactly is that passed to CAPO in your setup?
The issue has not occured on the clodus we tested this on -- looks like they are all starting VMs quickly enough ...

**Comment by JensAc** [comment]
I passed it like you're already proposing :slightly_smiling_face: 
https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/383/files#r1135091751
