### ISSUE TITLE
Waiting for Cloud-Init breaks capimgmt deployment on older images

### ISSUE THREAD

**Issue by flyersa** [SovereignCloudStack/k8s-cluster-api-provider#389]
Hi,

if we try to deploy the capi mgmt node on older images that needs alot of time for processing apt-get upgrade tasks it will break deployment with:

`╷
│ Error: file provisioner error
│
│   with openstack_compute_instance_v2.mgmtcluster_server,
│   on mgmtcluster.tf line 100, in resource "openstack_compute_instance_v2" "mgmtcluster_server":
│  100:   provisioner "file" {
│
│ Upload failed: wait: remote command exited without exit status or exit signal
╵
make: *** [Makefile:71: create] Error 1`

Almost everytime at exactly 2 minutes and 30 seconds after file provisioning was initiated. If i take a look at the VM itself it is processing dist upgrades (kernel etc, restarting stuff).

Problem happens with both Ubuntu 20.04 and 22.04 images. Maybe there is a fixed timeout or some process is killed that is required by the file provsioning?

The images in questions are not super old (maybe 1-2 months max) and run on magnetic, so yes it may take some time to process the dist upgrades. 

Version is latest git pull from today

**Comment by garloff** [comment]
I don't think that there was any change in our k8s-cluster-api-provider code that would cause this.
What happens if you add
```hcl
    timeout = 6min
```
into the `connection` block in `mgmtcluster.tf`?
This should address it ...

**Comment by flyersa** [comment]
sorry for late response. I actually tried again today without any change and an very old image, and it didnt break. Think maybe there was something really bad with that image on that environment that i tested it previously. But stil good to know with the timeout option. Thanks Kurt
