### ISSUE TITLE
Need updated k8s-capi images w/ Ubu 20.04

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#406]
The last Ubuntu 20.04 image on https://minio.services.osism.tech/openstack-k8s-capi-images has k8s version v1.26.1.
v1.26.3 is available, but only with Ubuntu 22.04.
Due to issues with 22.04 (cloud-init not working properly on subiquity-built images, but also excessive image size), we have not yet moved to 22.04 node images for SCS R4.
Details from @chess-knight, @matofeder.
We thus need the recent k8s image builds with 20.04 for the coming 6.5 months. (22.04 *in addition* to 20.04 would be nice for debugging and development purposes.)

I assume we will work on handing over the image build process @jschoone, @janiskemper, @batistein, but not in the next few weeks.

So we'd like to rely on your support again here, @berendt.

**Comment by garloff** [comment]
Hi Christian @berendt, your feedback and support here would be appreciated!

**Comment by berendt** [comment]
Build of Ubuntu 20.04 images re-enabled with https://github.com/osism/k8s-capi-images/pull/179.

Update of CAPI K8S images in OpenStack Image Manager with https://github.com/osism/openstack-image-manager/pull/550 (will be merged in around 30 minutes).

**Comment by garloff** [comment]
New images are available and have been tested successfully.
Latest updated with #410.
