### ISSUE TITLE
OpenStack LB Operating Status "Error" because of empty monitor port

### ISSUE THREAD

**Issue by Nils98Ar** [SovereignCloudStack/k8s-cluster-api-provider#411]
Hi,

we had problems with LBs that stopped working with Operating Status "Error".

After checking that the active amphora instance reaches the ingress controllers `NodePort` and `HealthCheck NodePort` ...

```
ubuntu@amphora-cd066efe-80d3-4d63-8b3a-4ffb373ad6c4:~$ sudo ip netns exec amphora-haproxy  nc -v 10.8.3.218 31666
Connection to 10.8.3.218 31666 port [tcp/*] succeeded!
ubuntu@amphora-cd066efe-80d3-4d63-8b3a-4ffb373ad6c4:~$ sudo ip netns exec amphora-haproxy  nc -v 10.8.3.218 31494
Connection to 10.8.3.218 31494 port [tcp/*] succeeded!
```

... i've found that the monitor port of the OpenStack LB member just wasn't configured. Adding it again fixed the issue.

<img src="https://user-images.githubusercontent.com/48221746/234226895-9ccc37bb-7ec9-48f5-8e1d-918fe2f1e424.png" width="400">

I assume that the Port was there in the past as the LB worked for three weeks. Do you have any idea why this config was lost?

Best regards
Nils

**Comment by Nils98Ar** [comment]
According to this the fix has been added with OCCM 1.24 and cherry-picked to 1.23.
https://github.com/kubernetes/cloud-provider-openstack/issues/1749

I will check our version of OCCM tomorrow.

If a new OCCM version helps I guess it‘s fixed with v5.X anyway.

**Comment by Nils98Ar** [comment]
We are running OCCM v1.23.0 and I guess the fix was cherry-picked to some later v1.23.X version.

I will upgrade everything to v5.X and see if it's fixed.

**Comment by garloff** [comment]
I also updated the maintained/v4.x and v4.0.x branches to have latest k8s and occm.
Note that these will very likely be the last changes to v4 branches.

**Comment by Nils98Ar** [comment]
Okay, I have started switching clusters to k8s v1.25 / R4 and it seems to be fixed.
