### ISSUE TITLE
Allow cluster operators to use custom container registry

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/k8s-cluster-api-provider#417]
As a cluster operator, I want to use a custom container registry that mirrors public registries e.g. to have a copy of container images under my own control or to avoid issues with [pull rate limit](https://docs.docker.com/docker-hub/download-rate-limit/) from docker.io registry. 

### Current state

SCS K8s bootstrap scripts install various k8s components and software, a few of them use docker.io public registry as a source.
The docker.io source is defined in their manifest files. Some of them are located in the k8s-cluster-api-provider repository, and some of them are downloaded on the fly from other git repositories. 

### Desired state

As was discussed in one SCS container team meeting we agreed that it is a good idea to use `registry.scs.community` as a mirror for `docker.io` and maybe also other container sources to avoid pull rate limit issues. 

### Open questions

1. Should we hard-code the SCS registry  `registry.scs.community` instead of docker.io in related manifest files which are located in the k8s-cluster-api-provider repository and also patch downloaded manifest files before they are applied?

2. Should we introduce variables that allow cluster operators to override docker.io occurrences from 1.? It means: keeping `docker.io` as a default and allowing cluster operators to change this default. 

3. Should we do the same (1. or 2.) for other registries like  `k8s.gcr.io` (i.e. not only docker.io)? 

4. User workload-related question: Should we set CRI (containerd) default registry to  `registry.scs.community`? or make this value also configurable? It means: if the user does not specify the container registry in his/her manifest file (e.g. image: nginx), the `registry.scs.community` will be used as a default registry instead of `docker.io`

Your feedback is welcome, @jschoone, @garloff, @chess-knight

**Comment by jschoone** [comment]
Hi @matofeder,
thank you for creating this issue.

1. My gut feeling says we should do this optionally and indepentent from using public registries. We could replace the `docker.io` occurrences with other equal registries, as the example in #414, the registry for calico can be quay as the images there are up-to-date.
2. If this is **one** variable this is not reliable, since not every image on `docker.io` is on the other registry we use instead. Currently it could work as I think every image we download from `docker.io` is available on `quay.io`, too.
3. Every `k8s.gcr.io` occurrence should be `registry.k8s.io` first, see #412 
4. Sounds good for now, this way we get our registry to be used. But to not get in conflict with 1. should that be configured as mirror first to have the original registry as fallback?

**Comment by Nils98Ar** [comment]
Maybe we should allow to configure the harbor registry as a transparent proxy cache/ mirror for all registries in containerd (management/ workload clusters) instead of patching k8s resources? 

That would also apply to other deployments in the workload clusters then: https://github.com/containerd/containerd/blob/main/docs/hosts.md#setup-default-mirror-for-all-registries

**Comment by matofeder** [comment]
@Nils98Ar 
> Maybe we should allow to configure the harbor registry as a transparent proxy cache/ mirror for all registries in containerd (management/ workload clusters) instead of patching k8s resources?

Agree! 

@jschoone 
> 4. Sounds good for now, this way we get our registry to be used. But to not get in conflict with 1. should that be configured as mirror first to have the original registry as fallback?

Yes it is possible, see my findings below. 

> 3. Every k8s.gcr.io occurrence should be registry.k8s.io first, see ..

I know, it was just example 

> 2. If this is one variable this is not reliable, since not every image on docker.io is on the other registry we use instead. Currently it could work as I think every image we download from docker.io is available on quay.io, too

If you configure the registry proxy cache to mirror e.g. docker.io without any restrictions (it is possible to restrict proxy cache to some specific images, tags ... ) then **all** images will be available through your registry proxy cache 

--- 
Containerd behavior:

See my findings from containerd investigation as IMO the containerd doc does not describe its behavior well 

- Default registry if the mirror of `docker.io` is configured
  - By default, containerd uses docker.io as a default registry, i.e. when just `nginx` is defined, containerd tries to find this image in `docker.io` registry
  - If the mirror to `docker.io` is configured, containerd uses this mirror as the first choice for the image search

- Fallback registry
    - If the mirror registry e.g. `origin-mirror` is configured to mirror/cache some registry e.g. `origin` and the `origin-mirror` registry is not available the `origin` registry is used as a fallback

containerd config (related part) used in my test
```
# cat /etc/containerd/config.toml
...
  [plugins."io.containerd.grpc.v1.cri".registry]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]

      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = ["https://registry.scs.community/v2/docker.io/"]  # docker.io mirror test

      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.scs.community"]
        endpoint = ["http://localhost:1234"]  # fallback test
...
```

---

Proposal:

- Configure containerd `docker.io` **mirror** to `registry.scs.community`
   - any docker.io image e.g. `nginx` or `docker.io/python` will be downloaded from `registry.scs.community`
   - `docker.io` is (automatically) used as a fallback if `registry.scs.community` is not available  

- Allow configuring containerd to mirror more registries e.g. `registry.k8s.io`

We would like to introduce a new variable called `containerd_registry_mirrors` which contains a list of registries and their mirrors, i.e:

```
containerd_registry_mirrors = ["docker.io;https://registry.scs.community/v2/docker.io/", "rrr.io;https://registry.scs.community/v2/rrr.io/"]  # list of semicolon-separated "<origin>;<mirror>" pairs
```

The default value of `containerd_registry_mirrors`  will be `["docker.io;https://registry.scs.community/v2/docker.io"]`. This ensures that  SCS registry will be used as a mirror for docker.io, by default.

**Comment by Nils98Ar** [comment]
> ```
> # cat /etc/containerd/config.toml
> ...
>   [plugins."io.containerd.grpc.v1.cri".registry]
>     [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
> 
>       [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
>         endpoint = ["https://registry.scs.community/v2/docker.io/"]  # docker.io mirror test
> 
>       [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.scs.community"]
>         endpoint = ["http://localhost:1234"]  # fallback test
> ...
> ```

@matofeder The registry.mirrors config seems to be deprecated, see the NOTE here: https://github.com/containerd/containerd/blob/main/docs/cri/registry.md#configure-image-registry

I think we have to do is this way: https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/417#issuecomment-1547201553

**Comment by matofeder** [comment]
> @matofeder The registry.mirrors config seems to be deprecated, see the NOTE here: https://github.com/containerd/containerd/blob/main/docs/cri/registry.md#configure-image-registry

True, the "new" format works as well, this "old" was used just for test purposes.

**Comment by matofeder** [comment]
> Proposal:
> 
>     * Configure containerd `docker.io` **mirror** to `registry.scs.community`
>       
>       * any docker.io image e.g. `nginx` or `docker.io/python` will be downloaded from `registry.scs.community`
>       * `docker.io` is (automatically) used as a fallback if `registry.scs.community` is not available
> 
>     * Allow configuring containerd to mirror more registries e.g. `registry.k8s.io`
> 
> 
> We would like to introduce a new variable called `containerd_registry_mirrors` which contains a list of registries and their mirrors, i.e:
> 
> ```
> containerd_registry_mirrors = ["docker.io;https://registry.scs.community/v2/docker.io/", "rrr.io;https://registry.scs.community/v2/rrr.io/"]  # list of semicolon-separated "<origin>;<mirror>" pairs
> ```
> 
> The default value of `containerd_registry_mirrors` will be `["docker.io;https://registry.scs.community/v2/docker.io"]`. This ensures that SCS registry will be used as a mirror for docker.io, by default.


The above proposal has been modified due to the reasons described below:

EDIT: Proposal:

Containerd allows configuring a bunch of options on container registry hosts (see containerd [docs](https://github.com/containerd/containerd/blob/main/docs/hosts.md)), e.g. client certs, CA certificates, header fields, capabilities ... 
Therefore, we decided to **not hardcode** the container registry host template, instead allow to pass the whole container registry config file and optionally also certificate files. 

Additional registry host config files and cert files for containerd could be passed through the `containerd_registry_files` terraform variable. This variable expects an object with two attributes:

- `hosts` attribute defines additional registry host config files for containerd.
The filename should reference the registry host namespace. Files defined in this set
will be copied into the `/etc/containerd/certs.d` directory on each workload cluster node
- `certs` attribute defines additional client and/or CA certificate files needed for
containerd authentication against registries defined by `hosts`. Files defined in this
set will be copied into the `/etc/containerd/certs` directory on each workload cluster node

The default value of the `containerd_registry_files` variable instructs containerd to use
`registry.scs.community` container registry instance as a public mirror of DockerHub
container registry. The default value is:

```bash
containerd_registry_files='{"hosts":["./files/containerd/docker.io"], "certs":[]}'
```
Default registry host config content:
```bash
$ cat ./files/containerd/docker.io
server = "https://registry-1.docker.io"

[host."https://registry.scs.community/v2/docker.io/"]
    capabilities = ["pull"]
    override_path = true
```

See https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/432 for further details

**Comment by Nils98Ar** [comment]
@matofeder @jschoone 

Can we add more registries that are mirrored by the SCS registry? Or at least a second one to demonstrate how additional registries can be added?
https://teuto.net/k8s/docs/managed-kubernetes/product-overview/#proxy-cache

Is it possible to replace `docker.io` in `https://registry.scs.community/v2/docker.io` with any upstream registry or does it require configuration on the SCS registry side?

**Comment by matofeder** [comment]
@Nils98Ar 

> Can we add more registries that are mirrored by the SCS registry? Or at least a second one to demonstrate how additional registries can be added? https://teuto.net/k8s/docs/managed-kubernetes/product-overview/#proxy-cache

Yes, I have already added some, see #447.
 
> Is it possible to replace `docker.io` in `https://registry.scs.community/v2/docker.io` with any upstream registry or does it require configuration on the SCS registry side?

It requires configuration on the SCS registry side as the registry "proxy-cache" project has to be configured on the SCS registry side.  #447 adds the following:

- ghcr.io
- quay.io
- registry.gitlab.com
- registry.k8s.io

Feel free to open an issue here if you want to add more registries.

**Comment by Nils98Ar** [comment]
How can this be configured for existing environments?
What needs to be done on the clustermgmt instance without re-deploying it via terraform?
