### ISSUE TITLE
Make use of HTTP and HTTPS proxy configurable

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/k8s-cluster-api-provider#418]
As an SCS Operator, I want to be able to configure the use of a corporate proxy in my Kubernetes clusters created by ClusterAPI.
Specifically I want to be able to specify the proxy settings in the ClusterAPI configuration and have these settings propagated to all nodes in the cluster during provisioning.

- [x] setup test proxy
- [x] introduce new config variable http_proxy

**Part1: mgmt host** (#620 )
- [x] /etc/profile mgmt host
- [x] apt for cloud-init
- [x] provisioning scripts
- [x] docker client mgmt host
- [x] docker daemon mgmt host

**Part2: worker and controlplane nodes** (#642)
- [x] ~~/etc/profile worker?~~
- [x] containerd worker
- [x] provisioning snippets (apt,curl...)
- [x] ~~kubelet worker~~

**Part3: Exceptions via `no_proxy`**
- [ ] create sensible defaults via pod,service and node cidr + k8s svc domain
- [ ] make additional entries configurabale via a new setting (document behaviour of both the default setting and additional entries)
- [ ] trickle down the settings to all places where http_proxy settings have been set

**Part4: Container workloads?**
- [ ] set env vars via mutatingwebhook

For now, i crossed /etc/profile from the list for the k8s-nodes. As /etc/profile is mostly used for login-shells. cluster-api managed-nodes are either created and provisioned automatically or deleted. Manual configuration via a login-shell (that would need proxy settings to be present in /etc/profile) is therefore unnecessary.

**Comment by mxmxchere** [comment]
Status Update: the current state in https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/620 is enough to successfully deploy a testcluster with proxy configured on mgmt and kind and all containers running on the mgmt host. Next, i will try to trickle down the proxy settings into the created cluster.

**Comment by Nils98Ar** [comment]
Thanks for the update!

**Comment by mxmxchere** [comment]
As it seems there is not really an option to tell containerd to use an http proxy. However i used an env where HTTP_PROXY was set and used nerdctl in it to start a containert. The image was pulled via the proxy then. So for now i think we can cross containerd off the list.

**Comment by mxmxchere** [comment]
wow, that was a super helpful link, i guess that they are doing it that way means also that this is sufficient. Yes this will only set proxy for imagepulls. But if we have set image-pulling and the other non-container traffic on the worker and controlplanes (there is some apt and curl, that needs proxying https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/f1d5610c1c72bab353ea7fa8cfd50b3095a1a94e/terraform/files/template/cluster-template.yaml#L253) this should be enough for part 2 and 3. We can have a look at in-container workloads  in a seperate step if necessary.

**Comment by Nils98Ar** [comment]
Perfect :)

**Comment by mxmxchere** [comment]
not done yet...

**Comment by mxmxchere** [comment]
yes i agree. Regarding the default set we could compose that of svc.cluster.local, local pod, service and node cidr at least.

**Comment by Nils98Ar** [comment]
@mxmxchere 
Hi Malte, is part 4 finished as well?

**Comment by mxmxchere** [comment]
Hi @Nils98Ar , as of now i think this is considered out of scope, maybe https://github.com/vmware-tanzu/cert-injection-webhook can solve this remaining issue?
