### ISSUE TITLE
Option to not use ephemeral disks

### ISSUE THREAD

**Issue by flyersa** [SovereignCloudStack/k8s-cluster-api-provider#421]
Hello,

is it possible with some config setting in clusterctl.yml to force capi on machine deployment to not use ephemeral disks?

There are usecases where you may want to not use local storage on hypervisors in case the hvs are not configured to use ceph for ephemeral.

If not that would be a nice feature if this can be implemented

**Comment by chess-knight** [comment]
Hello @flyersa,
can be this issue resolved by #423 linked to PR #424?

**Comment by garloff** [comment]
#424 should address this.
Note that #424 was implemented to ensure our k8s-capi solution works on all SCS clouds and we only have the flavors with local SSDs available as mandatory flavors in the valor spec v3, so had to improve the support of diskless flavors.
Note that local root disks are still a very reasonable choice for both k8s worker and control plane nodes. We normally don't want them to be live-migrated for example ...

**Comment by garloff** [comment]
I'll close this one -- please reopen if you disagree.
