### ISSUE TITLE
Support v3 flavors better

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#423]
As a k8s-capi user (self-managed clusters), I want default flavors that work on all SCS IaaS that comply to SCS-compatiable IaaS v3.

In particular this means:
(1) Leveraging the newly mandatory SCS-2V-4-20s flavors with local SSD for the control plane (etcd)
(2) Allowing the usage of diskless flavors by allocating a volume on the fly as needed for those flavors

Number (2) may be a duplicate of #421.

**Comment by garloff** [comment]
Part (1) is trivial and already implemented. Branch feat/flavors-v3
Part (2) - See https://cluster-api-openstack.sigs.k8s.io/topics/crd-changes/v1alpha4-to-v1alpha5.html#changes-to-rootvolume

**Comment by chess-knight** [comment]
@flyersa, @garloff, @Nils98Ar, this should probably be closed. Also, it has a R5 milestone!

And what about #421?

**Comment by garloff** [comment]
Closed by #424.
