### ISSUE TITLE
Additional args for cert-manager-controller container

### ISSUE THREAD

**Issue by Nils98Ar** [SovereignCloudStack/k8s-cluster-api-provider#463]
Hi,

we need additional args to configure the default issuer:
```
- --default-issuer-kind=ClusterIssuer
- --default-issuer-group=cert-manager.io
- --default-issuer-name=<Issuer Name>
```

And for extra configurationr regarding dns01 challenge:
```
- --dns01-recursive-nameservers-only
- --dns01-recursive-nameservers=<NS IP:Port>
```

Currently I am deploying cert-manager independently from k8s-cluster-api-provider as patching the running config via kustomize was not reliable enough.

Is there any chance to add parameters for this in k8s-cluster-api-provider?

Best regards
Nils

**Comment by fdobrovolny** [comment]
Hi @Nils98Ar, thank you very much for reporting the issue.

I will look into it.

**Comment by fdobrovolny** [comment]
@Nils98Ar

Could you please tell me more about your experience with trying to accomplish this via Kustomize and what the issue was? And maybe try to share the patch you were using?

**Comment by fdobrovolny** [comment]
So I discussed with @matofeder how to tackle this issue, and we have the following proposal. We would create an option called `cert_manager_extra_args` in the environment file in the format of a list or `;` separated string. We would copy it to `clusterctl.yaml` and then create a Kustomize patch leveraging json patch https://github.com/kubernetes-sigs/kustomize/issues/3265#issuecomment-732475022 that would be applied during cluster creation in the `apply_cert_manager.sh` script.

However, we would like to get @jschoone approval if it makes sense to add such an option.

In the meantime, you can use two options to achieve the same result depending if you want this on a per-cluster basis or for all clusters.

If you take a look in the script https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/main/terraform/files/bin/apply_cert_manager.sh#L16-L21 you can see it in more detail.

The flow is the following the scripts get called when `create_cluster.sh` is called, when using it manually or during the creation of the test cluster.

1. It uses cert-manager version as defined in `~/cluster-defaults/clusterctl.yaml`(created based on values in your environment file)
2. Checks if the given version manifest already exists in `~/kubernetes-manifests.d/cert-manager-${CERTMGR_VERSION}.yaml` if not it downloads it from `https://github.com/cert-manager/cert-manager/releases/download/${CERTMGR_VERSION}/cert-manager.yaml`
3. Takes the version from `~/kubernetes-manifests.d/cert-manager-${CERTMGR_VERSION}.yaml` and copies it over to `~/${CLUSTER_NAME}/deployed-manifests.d/cert-manager.yaml`
4. Applies the file `~/${CLUSTER_NAME}/deployed-manifests.d/cert-manager.yaml`

So now you have two options:
1. Per-cluster setting - After cluster creation, edit the file `~/kubernetes-manifests.d/cert-manager-${CERTMGR_VERSION}.yaml` and apply it manually again
2. For all clusters from there on - Edit the file `~/kubernetes-manifests.d/cert-manager-${CERTMGR_VERSION}.yaml` with your defaults and then all new clusters will use this version.

**Comment by Nils98Ar** [comment]
Maybe we should name it cert_manage_controller_extra_args as this is the name of the container that needs the args.

The json patch is not possible for running config with "kustomize.toolkit.fluxcd.io/ssa: merge" right?

When patching the cert-manager-${CERTMGR_VERSION}.yaml manually I have to remember doing this again for each new version ;)

Would it be possible to add the cert_manager_extra_args variable directly in the clusterctl.yaml and re-run create_cluster.sh for existing clusters?

**Comment by Nils98Ar** [comment]
I was doing it with a standard kustomization.yaml but maybe I should consider using the flux Kustomization CRD.

**Comment by jschoone** [comment]
@Nils98Ar is this still relevant?

**Comment by Nils98Ar** [comment]
Currently we are deploying cert-manager independently from k8s-cluster-api-provider. It works but supporting it in k8s-cluster-api-provider and ClusterStacks would be still cool.
