### ISSUE TITLE
Resources are not cleaned up

### ISSUE THREAD

**Issue by chess-knight** [SovereignCloudStack/k8s-cluster-api-provider#492]
#481 introduced separation of k8s clusters by namespace.
Clusters are now in a separate namespace(with the same name as the cluster itself).
It seems that this causes problems with all clean-up commands(`delete_cluster.sh`, `make fullclean` ...)  and maybe other scripts(`add_cluster-network.sh`, `enable-cilium-sg-kube.sh` ...) where the hardcoded value `default` is used.

For e.g. after using `make fullclean` command, network and router `k8s-clusterapi-cluster-testcluster-testcluster` were not deleted from the OpenStack project.

**Comment by garloff** [comment]
At least the fullclean case should have been revoeld by PR #498.

**Comment by fdobrovolny** [comment]
As #498 and #494 were merged, this should be done. @chess-knight will retest it together and close the issue if fixed.

**Comment by chess-knight** [comment]
It works for me, thanks
