### ISSUE TITLE
Jq not found after update

### ISSUE THREAD

**Issue by fdobrovolny** [SovereignCloudStack/k8s-cluster-api-provider#500]
In the PR #424 a new package is installed `jq` (https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/main/terraform/files/bin/bootstrap.sh#L24C29-L24C29). When having a machine created before this patch and then upgrading to the latest version this error arises when creating a cluster.

This, as part of #466  got merged into the `maintained/v5.x`. I just want to discuss whether we take the need for new software as a breaking change or not.

However, a few things should be addressed.

- [ ] Adding the installation of `jq` into the upgrade script.
- [ ] Documenting the need to install `jq` in docs or release notes for `maintained/v5.x` or consider removing the feature from the branch.

```
ubuntu@fd-mgmtcluster:~ [0]$ bin/create_cluster.sh testfd2
Switched to context "kind-kind".
> Cluster testfd2 does not exist. Creating a new cluster namespace...
namespace/testfd2 created
Context "kind-kind" modified.
> Namespace changed to testfd2
Adding docker.io/hosts.toml to the KubeadmControlPlane files
Adding docker.io/hosts.toml to the KubeadmConfigTemplate files
Switched to context "kind-kind".
> Cluster testfd2 does not exist, and new namespace creation is disabled.
#Created AppCred 11e495527840490da933ac524048b441
#Info: Changing OPENSTACK_CLOUD from testfd1 to fd-testfd2
Waiting for image ubuntu-capi-image-v1.25.11 to become active: d2619787-4d17-46d8-aa62-4f7c2969e47d active
Switched to context "kind-kind".
> Cluster testfd2 does not exist, and new namespace creation is disabled.
# show used variables for clustertemplate /home/ubuntu/testfd2/cluster-template.yaml
Adding server groups e246ed70-0fef-40f3-899d-8f1b00f2c339 and a785f99a-889a-4194-9b57-128bb82a76e6 to /home/ubuntu/testfd2/clusterctl.yaml
/home/ubuntu/bin/flavor_disk.sh: line 40: jq: command not found
/home/ubuntu/bin/flavor_disk.sh: line 44: jq: command not found
/home/ubuntu/bin/flavor_disk.sh: line 45: jq: command not found
/home/ubuntu/bin/flavor_disk.sh: line 47: jq: command not found
/home/ubuntu/bin/flavor_disk.sh: line 49: test: !=: unary operator expected
/home/ubuntu/bin/flavor_disk.sh: line 54: test: 0: unary operator expected
/home/ubuntu/bin/flavor_disk.sh: line 40: jq: command not found
/home/ubuntu/bin/flavor_disk.sh: line 44: jq: command not found
/home/ubuntu/bin/flavor_disk.sh: line 45: jq: command not found
/home/ubuntu/bin/flavor_disk.sh: line 47: jq: command not found
/home/ubuntu/bin/flavor_disk.sh: line 49: test: !=: unary operator expected
/home/ubuntu/bin/flavor_disk.sh: line 54: test: 0: unary operator expected
```

**Comment by garloff** [comment]
The breakage is not good of course. Sitting on maintained/v5.x, doing a git pull, you would not expect that your scripts stop working like they did.
OTOH, better supporting diskless flavors (as is the case with the backport) is a change that broadly matches the kind of improvements that fit v5.x (but not v5.0.x).
So clearly, the `flavor_disk.sh` script (at least for v5.x) should behave, e.g. by installing jq if it's not there or cleanly erroring out saying that you need to install it yourself if you want support for diskless flavors (and not break anything as long as you use the flavors with disks).

**Comment by garloff** [comment]
@fdobrovolny - will you take care of this?
Otherwise, I can certainly have a look; I don't foresee this to be a lot of work.

**Comment by fdobrovolny** [comment]
I will do it. I looked yesterday and will probably rewrite it to YQ just on the `v5.x` branch. What do you think about that? @garloff

**Comment by garloff** [comment]
jq is available as standard package on both Debian12 and Ubuntu2204 (and those two are the only supported options for the management host), so I don't see why a
```shell
if not type -p jq >/dev/null 2>&1; then
  if not sudo apt-get install jq; then
    echo "ERROR: jq is required but could not be installed"
    # cleanup needed?
    exit 10
  fi
fi
```
would not work. (untested code).

During bootstrapping the mgmt host, we need to have internet and pkg repo access as well, so we'll likely still have it.

In particular, I would want to avoid nontrivial amounts of code in `maintained/v5.x` that diverges from both `v5.0.0` and `main`.

**Comment by fdobrovolny** [comment]
Would you want something like that to be put towards the main branch and then merged towards the `maintained/v5.x` or only to the `maintained/v5.x`?
