### ISSUE TITLE
cilium-operator pod in CrashLoopBackOff

### ISSUE THREAD

**Issue by chess-knight** [SovereignCloudStack/k8s-cluster-api-provider#514]
```bash
$ k logs -n kube-system cilium-operator-b5695c56f-zt7nx
...
level=fatal msg="Failed to create gateway controller" error="failed to get API group resources: unable to retrieve the complete list of server APIs: gateway.networking.k8s.io/v1beta1: the server could not find the requested resource" subsys=gateway-controller
```
It looks like #503 doesn't work as expected.
I deployed the cluster with default settings but in the logs from creation I have:
```
terraform_data.mgmtcluster_bootstrap_files (remote-exec): # Deploy services (CNI, OCCM, CSI, Metrics, Cert-Manager, Flux2, Ingress)
terraform_data.mgmtcluster_bootstrap_files (remote-exec): ℹ️  Using Cilium version 1.14.0
terraform_data.mgmtcluster_bootstrap_files (remote-exec): 🔮 Auto-detected cluster name: democluster
terraform_data.mgmtcluster_bootstrap_files (remote-exec): 🔮 Auto-detected datapath mode: tunnel
terraform_data.mgmtcluster_bootstrap_files (remote-exec): 🔮 Auto-detected kube-proxy has not been installed
terraform_data.mgmtcluster_bootstrap_files (remote-exec): ℹ️  Cilium will fully replace all functionalities of kube-proxy
```
Probably these settings:
```
    --helm-set-string "kubeProxyReplacement=${DEPLOY_GATEWAY_API}" \
    --helm-set-string "gatewayAPI.enabled=${DEPLOY_GATEWAY_API}" \
```
[here](https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/main/terraform/files/bin/create_cluster.sh#L188) do not work correctly because of `Cilium will fully replace all functionalities of kube-proxy`.

**Comment by chess-knight** [comment]
@mxmxchere have you encountered this?

**Comment by NotTheEvilOne** [comment]
> @mxmxchere have you encountered this?

I'm sorry but he's on vacation. As far as I can remember Gateway API support strictly requires `kubeProxyReplacement` [1]. Furthermore requirements lists that CRDs must be applied manually:
```
The below CRDs from Gateway API v0.7.0 must be pre-installed. Please refer to this [docs](https://gateway-api.sigs.k8s.io/guides/?h=crds#getting-started-with-gateway-api) for installation steps. Alternatively, the below snippet could be used.
```

Looking at the code relevant the CRDs are added (in `./terraform/files/bin/`create_cluster.sh including the missing `v1beta1`) so I guess `DEPLOY_GATEWAY_API` is `false` (default):
```
if test "$USE_CILIUM" = "true" -o "${USE_CILIUM:0:1}" = "v"; then
  DEPLOY_GATEWAY_API=$(yq eval '.DEPLOY_GATEWAY_API' $CCCFG)
  if test "$DEPLOY_GATEWAY_API" = "true"; then
```

By default Cilium is not providing Gateway API either [2] so I wonder why the `gateway-controller` is starting up at all. Further investigation will be required. As a possible work around but also for future SCS requirements it may be an option to apply the CRDs in question even if not using the feature currently?

[1] https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#prerequisites
[2] https://github.com/cilium/cilium/blob/e00fb08477847464f490f7a3064e69ec9f8102a9/install/kubernetes/cilium/README.md?plain=1#L387

**Comment by chess-knight** [comment]
I think that the problem is in the *cilium install* command, because of this:
```bash
$ kubectl -n kube-system get cm cilium-config -oyaml | grep gateway-api
  enable-gateway-api: "true"
  enable-gateway-api-secrets-sync: "true"
  gateway-api-secrets-namespace: cilium-secrets
```
You can see Gateway API is enabled.
Also, kubeProxyReplacement should be set to false by default, but according to logs, it seems is not.

**Comment by NotTheEvilOne** [comment]
> I think that the problem is in the _cilium install_ command, because of this:
> 
> ```shell
> $ kubectl -n kube-system get cm cilium-config -oyaml | grep gateway-api
>   enable-gateway-api: "true"
>   enable-gateway-api-secrets-sync: "true"
>   gateway-api-secrets-namespace: cilium-secrets
> ```
> 
> You can see Gateway API is enabled. Also, kubeProxyReplacement should be set to false by default, but according to logs, it seems is not.

Could you please verify by chance if `DEPLOY_GATEWAY_API` is set to `true` of `false` when reaching line 179 [1] in create_cluster.sh as well as in line 192 [2]?

As mentioned before `kubeProxyReplacement` is set automatically to `true` if Gateway API is enabled (it's intended as it's required) but for you `DEPLOY_GATEWAY_API` should be set to `false` by default.

[1] https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/519da2738ce64793658a2e30456a5dbdaf44c6f8/terraform/files/bin/create_cluster.sh#L179
[2] https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/519da2738ce64793658a2e30456a5dbdaf44c6f8/terraform/files/bin/create_cluster.sh#L192

**Comment by garloff** [comment]
Some weird behaviour observed by @NotTheEvilOne:
- `DEPLOY_GATEWAY_API` should default to false, but does not?
- CRD should be applied but are not when `DEPLOY_GATEWAY_API` is `true`.

If `DEPLOY_GATEWAY_API` is not set to `true`, the `kubeProxyReplacement` should be disabled to avoid CNCF e2e tests (sonobuoy) to fail ...

**Comment by NotTheEvilOne** [comment]
Here's another result from my debugging:
`DEPLOY_GATEWAY_API` is set to `null` after `yq eval '.DEPLOY_GATEWAY_API' clusterctl.yaml` which is neither `true` nor `false`. That's one part of the reason why we observe the behaviour.

**Comment by chess-knight** [comment]
I tried adding `echo "${DEPLOY_GATEWAY_API}"` there and for me, it is `false`. But still, I see **Cilium will fully replace all functionalities of kube-proxy**

**Comment by chess-knight** [comment]
Okay I found a solution for the gateway API, the problem was in `--helm-set-string "gatewayAPI.enabled=${DEPLOY_GATEWAY_API}" \` line. It should not be a string but a boolean.

**Comment by chess-knight** [comment]
What is strange, is the lines `Auto-detected kube-proxy has not been installed` and `Cilium will fully replace all functionalities of kube-proxy`. But I see this:
```bash
$ kubectl -n kube-system get cm cilium-config -oyaml | grep replacement
  kube-proxy-replacement: "false"
  kube-proxy-replacement-healthz-bind-address: ""
$ kubectl -n kube-system exec ds/cilium -- cilium status | grep KubeProxyReplacement
KubeProxyReplacement:    False
$ helm get values cilium -n kube-system | grep Replacement
kubeProxyReplacement: "false"
```

**Comment by NotTheEvilOne** [comment]
I think we have multiple issues here:
1. If `DEPLOY_GATEWAY_API` is not set in `clusterctl.yaml` it returns `null`. Solution is to extend the `yq` expression.
2. If `DEPLOY_GATEWAY_API` is set it is not always handled as a bool and Helm handles everything not `false` as `true` including `"false"` with quotes. @chess-knight's solution should fix that one.
3. If `kube-proxy` is not detected at all by Cilium it sets `kubeProxyReplacement` automatically to true even if configured otherwise. I'm totally fine with that behaviour but we should find out if we want `kube-proxy` to be missing. That might be a separate issue.

**Comment by chess-knight** [comment]
@NotTheEvilOne, maybe we should keep `--helm-set-string kubeProxyReplacement` because of this https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/514#issuecomment-1700932026
