### ISSUE TITLE
Backport sprint Jena to `maintained` branches

### ISSUE THREAD

**Issue by fdobrovolny** [SovereignCloudStack/k8s-cluster-api-provider#532]
As per https://github.com/SovereignCloudStack/issues/issues/387.

The following PRs were merged:

| PR                                                                           | maintained/v5.x | maintained/v5.0.x |
|------------------------------------------------------------------------------|-----------------|-------------------|
| #545 Update release notes R5     |        :x:           |         :x:             |
| #549 Update default k8s to 1.27     |         :seedling:          |  :x:                |
| #547 Update flux release notes        |  :seedling:                  | :x:                 |
| #546 Update default cilium to 1.14.1        |  :seedling:                  |    :x:                |
| #540 Update default cert-manager to 1.12.4          |  :seedling:                  | :x:                 |
| #523 Enhance make create to use actual commit for checkout #522              |          :x:           |         :x:            |
| #539 Update helm to 3.12.3                                                   |       :seedling:            |        :seedling:             |
| #538 Fix missing value auth-url required for auth plugin password          |          :seedling:          |         :x:            |
| #542 Update default ingress-nginx to 1.8.1                                   |       :seedling:            |        :x:             |
| #544 Update default calico to 3.26.1                                        |        :seedling:          |         :seedling:             |
| #512 Doc: Gateway API                                                      |        :x: (#503)         |          :x:         |
| #537  Fix cilium install                                           |        :seedling:          |          :x:            |
| #528 Update k8s-harbor to v5.1.1                                            |        :seedling:          |          :x:            |
| #543 Update metrics-server to 0.6.4                                          |       :seedling:          |         :seedling:          |
| #536 Changed: replace usages of `apt` with `apt-get`                         |      :x:            |      :x:              |
| #524 flavor_disk.sh Installs jq when it is missing #500                       |        :seedling:          |          :x:            |
| #526 Feat/remove att volumes                                                 |              :x:     |   :x:                  |
| #525 Enhance documentation of the `update-R4-to-R5.sh` script #521           |         :x:        |          :x:         |
| #518 Add installation of jq into the `update-R4-to-R5.sh` and release notes  |          :x:       |           :x:        |
| #527 Fix harbor-settings no such file                                        |        :seedling:          |          :x:            |
| #515 Require terraform version < 1.6.0                                       |        :seedling:          |          :seedling:            |
| #513 Mention dNation in R5 Harbor release notes                              |        :seedling:          |          :x:            |
| #508 Detect yq being wrapper around jq and handle.                          |          :seedling:          |         :x:            |
| #509 Feat/support debian12                                                  |          :seedling:          |         :x:            |
| #510 Check and fail if prefix is in use                                      |          :seedling:          |         :x:            |
| #503 Enables ciliums implementation of Gateway API                           |        :x:        |          :x:         |
| #507 Update management node root volume and FIP naming #495                  |        :seedling:           |          :x:         |
| #497 Improve mng_cluster_ns.inc messaging #496                               |       :x:          |      :x:             |
| #502 Updates doc: default cilium version                                     |          :seedling:       |            :x:          |
| #501 Bumps cilium to v1.14.0 and cilium-cli to 0.15.0                        |       :seedling:       |      :x:                |

We should decide what should be backported if anything.

**Comment by chess-knight** [comment]
Close based on #659 and #660
