### ISSUE TITLE
Running `create_cluster.sh` and `delete_cluster.sh` in parallel results in unpredictable behavior

### ISSUE THREAD

**Issue by NotTheEvilOne** [SovereignCloudStack/k8s-cluster-api-provider#561]
While testing the R5-rc with multiple clusters I invoked in one session `create_cluster.sh testcluster2` while in another `delete_cluster.sh testcluster3`.

This resulted in multiple resources to be created in the `default` namespace instead of the separate one.

Short term solution would be to document that multiple invocations are currently not supported, long term to not expect the namespace switch to be permanent while execution of one script (e.g. by using `-n <namespace>`).

**Comment by NotTheEvilOne** [comment]
The branch `experiments/parallel-execution-of-scripts` adds a bash function to replace usage of `kubectl set-context` which is the main reason why running scripts multiple times result in unpredictable behavior like creation of clusters in namespace `default` etc.

I'm not satisfied with the result and looking for alternatives. Do you have any idea how readability and of course functionality can be further improved @fdobrovolny, @garloff, @chess-knight, @mxmxchere?

**Comment by garloff** [comment]
Always passing --context explicitly should help, no?

**Comment by NotTheEvilOne** [comment]
> Always passing --context explicitly should help, no?

Unfortunately not always or better to say, it's not enough. While experimenting I found three cases:
- Management host with cluster namespace set
- Cluster context
- Management host without cluster namespace set (e.g. `delete_cluster.sh` or by setting a different one explicitly like `capo-system`)

Adding `--context` and `--namespace` could be an option but would also touch nearly every `kubectl` line in all scripts.

**Comment by NotTheEvilOne** [comment]
I finally managed to get both `create_cluster.sh` and `delete_cluster.sh` working parallel [1] by utilizing temporary kubeconfig copies and build in `kubectl` logic.

Please let me know if you @garloff, @mxmxchere, @fdobrovolny, @chess-knight see any additional enhancement possibilities otherwise I'll add a PR for the latest variant.

[1] https://github.com/SovereignCloudStack/k8s-cluster-api-provider/compare/experiments/parallel-execution-of-scripts
