### ISSUE TITLE
Clusters  remain in PHASE Failed even if issues are resolved

### ISSUE THREAD

**Issue by Nils98Ar** [SovereignCloudStack/k8s-cluster-api-provider#565]
Is this a problem e.g. when moving the clusters to another capi mgmt cluster or do you know how to reset the PHASE status?

```
 (kind-kind) ubuntu@private-mgmtcluster:~/099-development$ kubectl get cluster
NAME              PHASE         AGE    VERSION
099-development   Failed        253d
099-pilot         Failed        257d
test-nils         Provisioned   83m
testcluster       Provisioned   20d
```
The problems occured quite a long time ago but the PHASE is still `Failed`.

```
Status:
  Conditions:
    Last Transition Time:  2023-08-23T21:53:49Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-12-30T16:08:22Z
    Status:                True
    Type:                  ControlPlaneInitialized
    Last Transition Time:  2023-08-23T21:53:49Z
    Status:                True
    Type:                  ControlPlaneReady
    Last Transition Time:  2022-12-30T16:06:36Z
    Status:                True
    Type:                  InfrastructureReady
  Control Plane Ready:     true
  Failure Domains:
    Nova:
      Control Plane:     true
  Failure Message:       Failure detected from referenced resource infrastructure.cluster.x-k8s.io/v1alpha6, Kind=OpenStackCluster with name "099-pilot": failed to reconcile load balancer: load balancer "k8s-clusterapi-cluster-default-099-pilot-kubeapi" with id 2e53445b-6724-4fca-ab7d-845ff47b5525 is not active after timeout: timed out waiting for the condition
  Failure Reason:        UpdateError
  Infrastructure Ready:  true
  Observed Generation:   3
  Phase:                 Failed
Events:                  <none>
```

**Comment by Nils98Ar** [comment]
@fdobrovolny 

I will try to reproduce it but the short version is:
- It is an „old“ management node (I think originally R2, currently R4) with all clusters in default ns
- there where infrastructure side rabbitmq related octavia LB issues in the past which have been resolved
- I have not moved anything yet but I ask myself if it could cause problems when moving the clusters in the future

The main question is if PHASE „Failed“ is even a problem and if it can be resetted to „Provisioned“ as the clusters are actually running without any issues and the problems have been resolved.

**Comment by chess-knight** [comment]
I found a related issue in CAPO kubernetes-sigs/cluster-api-provider-openstack#1574. They fixed it in v0.8.0.
Also, here is probably related CAPI issue kubernetes-sigs/cluster-api#7191.

IMO you can ignore that, or remove `failureReason` and `failureMessage` from the *.status* and most likely *phase* will be automatically set to *Provisioned*. Before that, double-check that all resources have no problems. You can also check `openstackcluster.status.network.apiServerLoadBalancer` if it is correct.

**Comment by chess-knight** [comment]
@Nils98Ar can this issue be closed based on https://github.com/SovereignCloudStack/k8s-cluster-api-provider/issues/565#issuecomment-1772567054?

**Comment by Nils98Ar** [comment]
Yes. I will re-open if it occurs again.
