### ISSUE TITLE
Bug: Having multiple external networks in a project does not work

### ISSUE THREAD

**Issue by Nils98Ar** [SovereignCloudStack/k8s-cluster-api-provider#572]
**Part 1: Terraform does not allow multiple external networks (`make create`)**
```
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│
│   with data.openstack_networking_network_v2.external,
│   on neutron.tf line 68, in data "openstack_networking_network_v2" "external":
│   68: data "openstack_networking_network_v2" "external" {
│
╵
make: *** [Makefile:87: create] Error 1
```
**Part 2: CAPO does not support name in `OPENSTACK_EXTERNAL_NETWORK_ID`**

Currently k8s-cluster-api-provider allows both (id/name) for `external ` according to the docs: https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/353c15c64118e15197a9367e6913e3c14196d078/doc/configuration.md?plain=1#L35C120-L35C120
(in the past an ID didn't even work but I have not tried again)

That results in the OPENSTACK_EXTERNAL_NETWORK_ID being an name which is not supported by CAPO
- https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/docs/book/src/development/development.md#support-for-clouds-with-multiple-external-networks
- https://github.com/SovereignCloudStack/k8s-cluster-api-provider/blob/353c15c64118e15197a9367e6913e3c14196d078/terraform/files/template/clusterctl.yaml.tmpl#L69

So CAPO does external network auto detection everytime and multiple external networks are not supported.

**Comment by chess-knight** [comment]
> **Part 1: Terraform does not allow multiple external networks (`make create`)**
> 
> ```
> ╷
> │ Error: Your query returned no results. Please change your search criteria and try again.
> │
> │   with data.openstack_networking_network_v2.external,
> │   on neutron.tf line 68, in data "openstack_networking_network_v2" "external":
> │   68: data "openstack_networking_network_v2" "external" {
> │
> ╵
> make: *** [Makefile:87: create] Error 1
> ```

I get the same error, when I use external network ID(*external = "ID"*) instead of Name(*external = "Name"*). It is expected because Terraform thinks it is still the name:
```terraform
data "openstack_networking_network_v2" "external" {
  name = var.external != "" ? var.external : data.openstack_networking_network_v2.extnet.name
}
```

In my opinion, we should distinguish the usage of Name versus ID. When specifying through Terraform, the Name of the network should be used, and when setting through *OPENSTACK_EXTERNAL_NETWORK_ID*, the ID of the network should be used.
We should also mention, that when multiple external networks are available, a user must specify the Name.

**Comment by Nils98Ar** [comment]
I think splitting it up into e.g. `external_id` and `external_name` makes sense.

Could we make terraform understand the id?
Or could we compute the name for terraform in the Makefile?
We could do the same thing for `OPENSTACK_EXTERNAL_NETWORK_ID` and compute the id in the Makefile if only the name is given.

In my opinion it would be more user-friendly to either only support the id or to allow both options (id and name in two separate variables) and compute the missing one.

**Comment by berendt** [comment]
I would like it very much if we could standardise such things and there could only be exactly one external network in an SCS project. The more special cases we support in the projects, the more complexity we have to include here. Would suggest discussing this in one of the SCS calls. I'm just not sure which one would be the best fit.

**Comment by chess-knight** [comment]
Hello @Nils98Ar, can you check #584 to see if that works for you?
