### ISSUE TITLE
Cinder Volume not deleted when PV deleted an still attached to instance

### ISSUE THREAD

**Issue by Nils98Ar** [SovereignCloudStack/k8s-cluster-api-provider#662]
After deleting the PVC/PV the cinder volume is not deleted and remains attached to the OpenStack instance.

Cluster rolling updates get stuck as CAPI waits for the CAPO OpenStackMachine to be deleted after it was drained which does not happen because there are still volumes from deleted PVs attached to the OpenStack instance. The CAPI Machine  remains in state DELETING.

The rolling update continues after deleting the instances in OpenStack manually as soon as the associated CAPI Machine is in state DELETING.

**Comment by Nils98Ar** [comment]
I will look into it tomorrow. Maybe someone already has an idea ;)

**Comment by jschoone** [comment]
Hi @Nils98Ar, we're currently a bit on low capacity. Could you describe the flow with the commands you executed to reproduce it?

**Comment by Nils98Ar** [comment]
Could not reproduce it right now. Maybe the volumes were old ones and the problem was already resolved in the past.

I will re-open the issue if it occurs again.
