### ISSUE TITLE
Create OVN LB by default

### ISSUE THREAD

**Issue by chess-knight** [SovereignCloudStack/k8s-cluster-api-provider#706]
Consider OVN LB as a default based on #687

**Comment by garloff** [comment]
Can we also get the LB in front of kube-api to use OVN?
Not requiring amphorae would be a real advantage:
While not as feature rich, OVN LBs do only require a fraction of the resources of amphorae.
And have the advantage of being less fragile (just saying `PENDING_CREATE` here) and providing the source IP without any proxy protocol and nip.io hacks.

**Comment by chess-knight** [comment]
It seems like it is supported in CAPO from [v0.7.2](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/releases/tag/v0.7.2). I tried it locally, and it works for me. See #720, where I try it together with ovn lb in front of ingress-nginx.

**Comment by garloff** [comment]
Nice -- this would be a very nice supported setting and probably a good default (if we can get enough test coverage to validate that it's as solid as we expect).
