### ISSUE TITLE
Permissions of ~/.kube/config too open

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/k8s-cluster-api-provider#8]
THe file ~/.kube/config on the kind node have permissions 0644.
This is not what I expect from a file containing credentials. Bad example.
(It may or may not be a concrete risk depending on the access situation, as you can argue that access to the kind node should not be granted to folks who are not normally allowed to use the capi. But this file might also be copied over (using scp -p or rsync) and the too permissive setting might be replicated elsewhere where it makes a difference.)

**Comment by mxmxchere** [comment]
closed by #9
