### ISSUE TITLE
yq has no flaq --yaml-output ?

### ISSUE THREAD

**Issue by flyersa** [SovereignCloudStack/k8s-cluster-api-provider#81]
Hello,

im trying to follow up on the instructions, created the .tf file with all values, but when i run make create i get the error from yq which i installed using snap on ubuntu 20.04 that it does not support --yaml-output

make create
Error: unknown flag: --yaml-output

?

**Comment by curx** [comment]
Hi @flyersa,

you need the `python3-yq` package, the snap installs another YAML tool but has another options.

**Comment by flyersa** [comment]
ok will try, thank you. Documentation said python3-yq OR snap ;)

**Comment by garloff** [comment]
Addressed by merged PR #82.
